### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by van-de-bugger** [Perl-Toolchain-Gang/Software-License#41]
name

    This method returns the name of the license, suitable for
    shoving in the middle of a sentence, generally with a leading
    capitalized "The."

If the name of license is suitable for showing in the *middle* of a sentence, why "the" article is *capitalized*?

**Comment by rjbs** [comment]
I don't know.  I guess it's like "I saw a concert by the Beatles" vs. "I saw a concert by The Beatles."

I guess we could merge something to change this, but I'd call it very low priority indeed.
